# Generated by Django 4.0 on 2021-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='administrator',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user_login',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
