# Generated by Django 4.0 on 2021-12-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
